build: false
shallow_clone: false
platform: 'x86'
clone_folder: C:\projects\utf8
branches:
  except:
    - gh-pages

install:
  - cinst -y curl
  - cinst -y OpenSSL.Light
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - cinst -y php
  - cd C:\tools\php\ext
  - curl -O https://xdebug.org/files/php_xdebug-2.4.1-7.0-vc14-nts-x86_64.dll
  - cd C:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo zend_extension_ts=php_xdebug-2.4.1-7.0-vc14-nts-x86_64.dll >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  - cd C:\projects\utf8
  - mkdir build\logs
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - curl -O https://scrutinizer-ci.com/ocular.phar
  - php composer.phar config -g github-oauth.github.com %GITHUB_TOKEN%
  - php composer.phar self-update
  - php composer.phar require satooshi/php-coveralls:dev-master
  - php composer.phar install --prefer-dist --no-interaction
  - php composer.phar dump-autoload -o

test_script:
  - cd C:\projects\utf8
  - php.exe --version
  - dir
  - php.exe vendor\phpunit\phpunit\phpunit -c phpunit.xml
  - php.exe ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
